name = "server-gcloud" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "gcloud.mosyaf.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.gcloud.mosyaf.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.staging.vidio.com.gcloud.mosyaf.us.kg"
custom_domain = true
[[routes]]
pattern = "img.email3.vidio.com.gcloud.mosyaf.us.kg"
custom_domain = true
[vars]
# UUID = "4353e26d-98dd-408e-a7f4-b2c4e35e1e10"
# PROXYIP = "35.219.15.90"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "4353e26d-98dd-408e-a7f4-b2c4e35e1e10"
